---
- name: Check if Kitty terminal is already installed
  ansible.builtin.command: which kitty
  register: already_installed
  failed_when: false
  changed_when: false

- name: Install Kitty terminal emulator
  ansible.builtin.shell: |
    set -o pipefail && curl -fsSL https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  when: already_installed.rc != 0
  changed_when: true

- name: Display Kitty installation status
  ansible.builtin.debug:
    msg: "Kitty terminal emulator is already installed and available"
  when: already_installed.rc == 0
