[manager]
cwd = { fg = "red" } 

[mode]
normal_main = { fg = '#0a0c10', bg = 'blue' } 
select_main = { fg = '#0a0c10', bg = 'yellow' }
unset_main  = { fg = '#0a0c10', bg = 'green' }

normal_alt  = { fg = '#0a0c10', bg = 'blue', reversed = true} 
select_alt  = { fg = '#0a0c10', bg = 'yellow', reversed = true }
unset_alt   = { fg = '#0a0c10', bg = 'green', reversed = true }

[status]
separator_open  = ""
separator_close = ""

[filetype]
rules = [{ name = "*/", fg = "white" }]
